import { PaymentClaimForm } from "@/components/business/payment-claim-form";
import { requireUser, hasBusinessPermission } from "@/lib/auth/authorization";
import { getOwnerBilling } from "@/lib/data/owner-billing";

function money(amountMinor: number, currency: string) {
  return new Intl.NumberFormat("en", { style: "currency", currency }).format(amountMinor / 100);
}

export default async function BillingPage({ params, searchParams }: { params: Promise<{ businessId: string }>; searchParams: Promise<{ saved?: string }> }) {
  const { businessId } = await params;
  const { saved } = await searchParams;
  const user = await requireUser(`/business/${encodeURIComponent(businessId)}/billing`);
  const [billing, canSubmit] = await Promise.all([
    getOwnerBilling(user.id, businessId),
    hasBusinessPermission(user.id, businessId, "billing.manage_billing"),
  ]);
  const openInvoices = billing.invoices.filter((invoice) => invoice.status === "OPEN" || invoice.status === "OVERDUE");
  return (
    <div className="space-y-8">
      <header><p className="text-sm font-semibold uppercase tracking-[0.18em] text-emerald-700">Subscription</p><h1 className="mt-2 text-3xl font-bold text-emerald-950">Billing & Mobile Money</h1><p className="mt-2 text-slate-600">Payment is claimed externally and confirmed manually by an administrator. No exchange rate is inferred.</p></header>
      {saved ? <div className="rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-sm text-emerald-800">Payment claim submitted for review.</div> : null}
      {billing.currencyMismatch.present ? <div className="rounded-xl border border-rose-200 bg-rose-50 p-4 text-sm text-rose-800">{billing.currencyMismatch.message}</div> : null}
      <section className="grid gap-5 sm:grid-cols-2 xl:grid-cols-4">
        <div className="rounded-2xl border border-emerald-100 bg-white p-5"><p className="text-sm text-slate-600">Status</p><p className="mt-2 font-bold text-emerald-950">{billing.subscription.status.replaceAll("_", " ")}</p></div>
        <div className="rounded-2xl border border-emerald-100 bg-white p-5"><p className="text-sm text-slate-600">Plan</p><p className="mt-2 font-bold text-emerald-950">{billing.subscription.planNameSnapshot}</p></div>
        <div className="rounded-2xl border border-emerald-100 bg-white p-5"><p className="text-sm text-slate-600">Amount</p><p className="mt-2 font-bold text-emerald-950">{money(billing.subscription.amountMinor, billing.subscription.currency)} / {billing.subscription.interval.toLowerCase()}</p></div>
        <div className="rounded-2xl border border-emerald-100 bg-white p-5"><p className="text-sm text-slate-600">Due</p><p className="mt-2 font-bold text-emerald-950">{new Date(billing.subscription.dueDate).toLocaleString()}</p></div>
      </section>
      <section className="rounded-2xl border border-emerald-100 bg-white p-6"><h2 className="text-xl font-bold text-emerald-950">Configured payment instructions</h2><dl className="mt-5 grid gap-5 sm:grid-cols-2 lg:grid-cols-4 text-sm"><div><dt className="text-slate-600">Provider</dt><dd className="mt-1 text-emerald-950">{billing.settings.momoProvider ?? "Not configured"}</dd></div><div><dt className="text-slate-600">Recipient</dt><dd className="mt-1 text-emerald-950">{billing.settings.momoRecipientName ?? "Not configured"}</dd></div><div><dt className="text-slate-600">Merchant code</dt><dd className="mt-1 text-emerald-950">{billing.settings.momoMerchantCode ?? "Not configured"}</dd></div><div><dt className="text-slate-600">Country</dt><dd className="mt-1 text-emerald-950">{billing.settings.momoCountry ?? "Not configured"}</dd></div></dl>{billing.settings.paymentInstructions ? <p className="mt-5 whitespace-pre-wrap rounded-xl border border-emerald-600 bg-emerald-50 p-4 text-sm text-emerald-800">{billing.settings.paymentInstructions}</p> : <p className="mt-5 rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-800">No payment instructions are configured. Do not send money until a Super Admin configures them.</p>}<p className="mt-4 text-xs text-slate-600">Reference format: {billing.settings.referenceFormat} · Review target: {billing.settings.claimReviewDays} days · Grace: {billing.settings.gracePeriodDays} days</p></section>
      {canSubmit ? <section><h2 className="mb-4 text-xl font-bold text-emerald-950">Submit a payment claim</h2><PaymentClaimForm businessId={businessId} invoices={openInvoices} instructions={billing.settings.paymentInstructions} currencyMismatch={billing.currencyMismatch.message} /></section> : null}
      <section className="space-y-4"><h2 className="text-xl font-bold text-emerald-950">Invoices</h2><div className="overflow-x-auto rounded-2xl border border-emerald-100"><table className="w-full text-left text-sm"><thead className="bg-white text-slate-600"><tr><th className="px-4 py-3">Invoice</th><th className="px-4 py-3">Amount</th><th className="px-4 py-3">Due</th><th className="px-4 py-3">Status</th></tr></thead><tbody className="divide-y divide-emerald-100">{billing.invoices.map((invoice) => <tr key={invoice.id}><td className="px-4 py-3 text-emerald-950">{invoice.number}</td><td className="px-4 py-3 text-slate-700">{money(invoice.amountMinor, invoice.currency)}</td><td className="px-4 py-3 text-slate-700">{new Date(invoice.dueDate).toLocaleDateString()}</td><td className="px-4 py-3 text-slate-700">{invoice.status}</td></tr>)}</tbody></table></div></section>
      <section className="space-y-4"><h2 className="text-xl font-bold text-emerald-950">Payment claims</h2>{billing.claims.length === 0 ? <p className="rounded-xl border border-dashed border-emerald-100 p-5 text-sm text-slate-600">No payment claims have been submitted.</p> : <div className="space-y-3">{billing.claims.map((claim) => <article key={claim.id} className="rounded-xl border border-emerald-100 bg-white p-4"><div className="flex flex-wrap justify-between gap-3"><div><p className="font-semibold text-emerald-950">{claim.reference}</p><p className="mt-1 text-sm text-slate-600">Sent {new Date(claim.sentAt).toLocaleString()} · {money(claim.amountMinor, claim.currency)}</p></div><span className="rounded-full border border-emerald-200 px-3 py-1 text-xs text-slate-700">{claim.status.replaceAll("_", " ")}</span></div>{claim.proofAvailable ? <a className="mt-3 inline-block text-sm font-semibold text-emerald-700" href={`/api/files/claims/${encodeURIComponent(claim.id)}`}>Download proof</a> : null}{claim.decisionReason ? <p className="mt-3 text-sm text-amber-800">Decision: {claim.decisionReason}</p> : null}</article>)}</div>}</section>
      <section className="space-y-4"><h2 className="text-xl font-bold text-emerald-950">Confirmed receipts</h2>{billing.receipts.length === 0 ? <p className="rounded-xl border border-dashed border-emerald-100 p-5 text-sm text-slate-600">No confirmed payment receipts exist.</p> : <div className="space-y-3">{billing.receipts.map((receipt) => <article key={receipt.id} className="flex flex-wrap justify-between gap-3 rounded-xl border border-emerald-100 p-4"><div><p className="font-semibold text-emerald-950">{receipt.receiptNumber}</p><p className="mt-1 text-sm text-slate-600">{receipt.reference} · {new Date(receipt.confirmedAt).toLocaleString()}</p></div><p className="font-semibold text-emerald-700">{money(receipt.amountMinor, receipt.currency)}</p></article>)}</div>}</section>
    </div>
  );
}
